function [T, Vf] = importDTAfile(filename, dataLines)
%IMPORTFILE Import data from a text file
%  [T, VF] = IMPORTFILE(FILENAME) reads data from text file FILENAME for
%  the default selection.  Returns the data as column vectors.
%
%  [T, VF] = IMPORTFILE(FILE, DATALINES) reads data for the specified
%  row interval(s) of text file FILENAME. Specify DATALINES as a
%  positive scalar integer or a N-by-2 array of positive scalar integers
%  for dis-contiguous row intervals.
%
%  Example:
%  [T, Vf] = importfile("E:\Gamry\ICMS_Sept13\ICMS20_D30_2uA.DTA", [94, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 14-Sep-2021 16:13:11

%% Input handling

% If dataLines is not specified, define defaults
% 94
if nargin < 2
    dataLines = [68, Inf]; %129 68
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 11);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = "\t";

% Specify column names and types
opts.VariableNames = ["Var1", "Var2", "T", "Vf", "Var5", "Var6", "Var7", "Var8", "Var9", "Var10", "Var11"];
opts.SelectedVariableNames = ["T", "Vf"];
opts.VariableTypes = ["string", "string", "double", "double", "string", "string", "string", "string", "string", "string", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["Var1", "Var2", "Var5", "Var6", "Var7", "Var8", "Var9", "Var10", "Var11"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Var1", "Var2", "Var5", "Var6", "Var7", "Var8", "Var9", "Var10", "Var11"], "EmptyFieldRule", "auto");

% Import the data
tbl = readtable(filename, opts);

%% Convert to output type
T = tbl.T;
Vf = tbl.Vf;
end